title: Your Fight Site
email: "&#x69;n&#x66;o&#64;y&#x6f;&#117;&#114;&#x66;&#x69;&#x67;&#x68;&#116;s&#x69;&#116;e.&#99;&#x6f;&#x6d;"

plugins:
  - jekyll-paginate
  - jekyll-redirect-from

exclude:
  - CNAME
  - node_modules
  - package.json

sass:
  style: compressed

collections:
  projects:
    output: true

  training_schools:
    output: false

prices:
  web_design:
    setup: 99
    subscription: 4.99

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
  -
    scope:
      path: ""
      type: "training_schools"
    values:
      country: GB

permalink: "/news/:year/:month/:day/:slug"
