# Site settings
title: Your Fight Site
url: "http://www.yourfightsite.com"
baseurl: ""

# Build settings
markdown: kramdown

collections:
  projects:
    category: "Web Design"
    industry: "Pro Wrestling"
    output: true

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: project
